script_dir=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)

#source
source $script_dir/iterm2_shell_integration.zsh

# Alias
alias open="open -g"
alias update_system="brew update; brew upgrade; brew cleanup; brew doctor"
alias lsusb="system_profiler SPUSBDataType"
alias arduino='open /Applications/Arduino.app'
alias ps='ps -T'

# Environment variable
export PATH="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/texlive/2016/bin/x86_64-darwin/:$PATH"
