#!/bin/zsh
echo "\x1b[32mip addr\x1b[39m"
ip addr
echo "\x1b[32mip route\x1b[39m"
ip route
echo "\x1b[32mping -c 1 8.8.8.8\x1b[39m"
ping -c 1 8.8.8.8
echo "\x1b[32mping6 -c 1 2001:4860:4860::8888\x1b[39m"
ping6 -c 1 2001:4860:4860::8888
echo "\x1b[32mdig -4 A google.co.jp +short\x1b[39m"
dig -4 A google.co.jp +short
echo "\x1b[32mdig -4 AAAA google.co.jp +short\x1b[39m"
dig -4 AAAA google.co.jp +short
echo "\x1b[32mdig -6 AAAA google.co.jp +short\x1b[39m"
dig -6 AAAA google.co.jp +short
