#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import subprocess
import os.path

if len(sys.argv) != 3 :
  print("Usage: %s filesize filename"%sys.argv[0])

if sys.argv[1][-1] == "k" :
  filesize = int(sys.argv[1][:-1])*1024
elif sys.argv[1][-1] == "M" :
  filesize = int(sys.argv[1][:-1])*1024*1024
else :
  filesize = int(sys.argv[1])
filename = sys.argv[2]
print(filename)

while os.path.getsize(filename) > filesize :
  tmp_filename = filename.replace('/', '_')
  p = subprocess.Popen(['convert', '-resize', '80%', filename, '/tmp/'+tmp_filename],
                    stdin=sys.stdin,
                    stdout=sys.stdout,
                    stderr=sys.stderr)
  if p.wait() != 0 :
    sys.exit(1)
  os.remove(filename)
  os.rename('/tmp/'+tmp_filename, filename)
# find . -name "*.jpg" -o -name "*.JPG" -o -name "*.png" -type f -print0 | xargs -n 1 -0 resize.py 1000k
